"""empty message

Revision ID: 426cafce8768
Revises: 
Create Date: 2023-03-31 19:56:30.024151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426cafce8768'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ability', sa.String(), nullable=True),
    sa.Column('base_stats_hp', sa.Integer(), nullable=True),
    sa.Column('base_stat_defense', sa.Integer(), nullable=True),
    sa.Column('sprites', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('captured_pokemon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['captured_pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
