"""empty message

Revision ID: d5a391591542
Revises: 41c7afc815cd
Create Date: 2023-03-10 19:32:34.938759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a391591542'
down_revision = '41c7afc815cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catch_pokemon',
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catch_pokemon')
    # ### end Alembic commands ###
